# packages and sources

library(ape)
library(autoNumCaptions)
library(car)
library(caret)
library(cowplot)
library(data.table)
library(flextable)
library(ggbeeswarm)
library(gridExtra)
# library(gt)
# library(kableExtra)
library(knitr)
library(lme4)
library(MASS)
library(nortest)
library(phyloseqCompanion)
library(picante)
library(pROC)
library(RColorBrewer)
library(rcompanion)
library(recipes)
library(RedoControl)
library(stringi)
library(stringr)
library(tidyverse)
library(usedist)
library(vegan)

write_bib(file = paste0("Saved_objects/Citations_history/package_citations_", Sys.Date(), ".bib"))
